FROM python:3.10-slim

WORKDIR /app

COPY requirements_api.txt .
RUN pip install --no-cache-dir -r requirements_api.txt

COPY model_api.py .

CMD ["uvicorn", "model_api:app", "--host", "0.0.0.0", "--port", "8000"]